Repository codestates-seb/seb40_main_033, pull requests merged in 2022-12, with the labels that each got.

#154 [Server] MdPick(최신순) 모아보기 기능 구현
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지수

#156 [Client] 상세페이지 API 적용
  client/src/components/Etc/Price.js
  client/src/components/Etc/Tag.js
  client/src/pages/Detail.js
Labels: ✨ feat, [FE] 김세연

#158 [Client] 회원정보 수정 구현
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PayPageContainer.js
  client/src/components/Etc/Price.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/WishListCards.js
  client/src/components/Stars/TextStar.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
Labels: ✨ feat, 💄 design, [FE] 도현수

#159 [Client] 필터 기능 추가 및 api 적용
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Search/Search.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/ItemList.js
  client/src/pages/SearchList.js
  client/src/redux/slice/filterSlice.js
  client/src/redux/store/store.js
Labels: ✨ feat, 💄 design, [FE] 안지환

#160 [Server] 회원 정보 수정 관련 오류 수정, 정기 구독 오류 수정
  server/build.gradle
  server/src/main/java/server/team33/cart/entity/Cart.java
  server/src/main/java/server/team33/item/entity/Brand.java
  server/src/main/java/server/team33/jasyptConfig/JasyptConfig.java
  server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/filter/JwtVerificationFilter.java
  server/src/main/java/server/team33/login/handler/UserAuthFailureHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/server/team33/logout/Logout.java
  server/src/main/java/server/team33/order/mapper/OrderMapper.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/redis/RedisConfig.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/job/KaKaoSubscriptionJob.java
  server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
  server/src/main/java/server/team33/talk/controller/TalkController.java
  server/src/main/java/server/team33/talk/service/TalkService.java
  server/src/main/java/server/team33/user/mapper/UserMapper.java
  server/src/main/java/server/team33/user/service/UserInfoFilter.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/test/java/server/team33/jasyptConfig/JasyptConfigTest.java
Labels: 🐛 fix, ♻️ refactor, [BE] 최민석

#163 [Server] 로그인한 유저의 찜한 상품 IdList 조회 기능 구현
  server/src/main/java/server/team33/jasyptConfig/JasyptConfig.java
  server/src/main/java/server/team33/wish/controller/WishController.java
  server/src/main/java/server/team33/wish/repository/WishRepository.java
  server/src/main/java/server/team33/wish/service/WishService.java
Labels: ✨ feat, [BE] 김지수

#164 [Server] 로그인 시 유저 아이디 제공
  server/build.gradle
  server/src/main/java/server/team33/login/filter/JwtLoginFilter.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: ✨ feat, [BE] 최민석

#166 [Client] 쿼리 invalidate, 로컬스토리지 토큰 불러오기
  client/src/components/Forms/DefalutForm.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Modals/ReviewModal.js
  client/src/hooks/useFetch.js
  client/src/hooks/useLogIn.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/UserInfo.js
  client/src/redux/slice/userSlice.js
Labels: ✨ feat, [FE] 방기현

#167 [Server] 리뷰에서 구매 수량을 확인할 수 있도록 quantity 필드 추가
  server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/review/controller/ReviewController.java
  server/src/main/java/server/team33/review/dto/ReviewDetailResponseDto.java
  server/src/main/java/server/team33/review/entity/Review.java
  server/src/main/java/server/team33/review/mapper/ReviewMapper.java
Labels: ✨ feat, [BE] 김지효

#169 [Server] 아이템 목록 낮은가격순 정렬 기능 구현
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지효

#171 [Client] 상세페이지 장바구니 담기, 바로 결제하기 API 적용
  client/src/components/Etc/Tag.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/TabButtons.js
  client/src/hooks/usePurchase.js
  client/src/pages/Detail.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/OrderDetail.js
Labels: ✨ feat, [FE] 도현수, [FE] 김세연

#172 [Server] 메인페이지 종류별 9개씩 불러오는 쿼리 수정
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: 🐛 fix, [BE] 김지수

#174 [Client]로그아웃, 회원탈퇴 시 로컬스토리지 초기화 구현
  client/src/components/Etc/MyPageHeader.js
  client/src/pages/MyPages/UserInfo.js
  client/src/redux/slice/nickNameSlice.js
  client/src/redux/slice/userSlice.js
  client/src/redux/store/store.js
Labels: ✨ feat, [FE] 도현수

#175 [Client] 탭 버튼 props로 onClick 전달하지 않은 경우에 발생하는 에러 해결
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Tabs/DefaultTabButton.js
Labels: 🐛 fix, [FE] 김세연

#177 [Client] 결제기능 구현
  client/src/components/Etc/DefaultPayment.js
  client/src/components/Etc/PayDestination.js
  client/src/components/Etc/PayInfo.js
  client/src/components/Etc/PayItemInformation.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/Price.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/PayLists.js
  client/src/pages/Payment.js
  client/src/pages/SubPayment.js
Labels: ✨ feat, [FE] 도현수

#178 [Client] 마이페이지 주문내역 페이지, 주문내역 상세페이지 API 적용
  client/src/components/Etc/PayInfo.js
  client/src/components/Etc/Price.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/pages/MyPages/OrderDetail.js
Labels: ✨ feat, 💄 design, [FE] 김세연

#179 [Client] 장바구니 기능 구현 중
  client/src/components/Etc/PageTitle.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/SmallListCards.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
Labels: ✨ feat, [FE] 안지환

#181 [Client] 위시리스트 버튼 API 적용
  client/src/components/Buttons/WishlistButton.js
  client/src/hooks/useFetch.js
  client/src/pages/MyPages/OrderDetail.js
Labels: 🐛 fix, ✨ feat, [FE] 도현수, [FE] 김세연

#183 [Client] 작성글관리, 장바구니 페이지 구현
  client/src/components/Forms/UpdateTalkForm.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/PayLists.js
  client/src/components/Modals/CancelModal.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Stars/BtnStar.js
  client/src/components/Stars/TextStar.js
  client/src/components/Talk/MyPageTalk.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPage.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
  client/src/pages/MyPages/OrderDetail.js
Labels: 🐛 fix, ✨ feat, 💄 design, [FE] 방기현

#185 [Server] api 권한 설정, jwt 예외 처리 수정
  server/build.gradle
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/filter/JwtVerificationFilter.java
  server/src/main/java/server/team33/login/handler/UserAccessDeniedHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthFailureHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthenticationEntryPoint.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/resources/application.yml
Labels: 🐛 fix, ✨ feat, [BE] 최민석

#188 [Server] 정기 구독 목록 수정, 장바구니 항목 삭제 기능 수정
  server/src/main/java/server/team33/cart/controller/ItemCartController.java
  server/src/main/java/server/team33/cart/service/ItemCartService.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/dto/ItemOrderDto.java
  server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
  server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/subscription/trigger/TriggerService.java
Labels: 🐛 fix, [BE] 김지효

#186 [Client] 정기장바구니 배송주기 변경 API 연결, 탭버튼 수정
  client/.eslintrc.json
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/TabButtons.js
Labels: ✨ feat, [FE] 방기현

#189 [Client] 상품 검색 목록 작업
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortAndSearchButtons.js
  client/src/components/Etc/PageTitle.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Search/Search.js
  client/src/pages/SearchList.js
Labels: ✨ feat, [FE] 안지환

#191 [Client] 상품목록 필터링, 정렬 구현 외
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Categories/Categories.js
  client/src/components/Etc/BrandsWindow.js
  client/src/components/Etc/PageTitle.js
  client/src/components/Etc/Price.js
  client/src/components/Lists/MainListCard.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Search/Search.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/ItemList.js
  client/src/pages/SearchList.js
  client/src/redux/slice/filterSlice.js
  client/src/utils/paramsMaker.js
Labels: 💚 chore, ✨ feat, [FE] 방기현, 🎨 style

#193 [Client] 작성글관리 페이지 및 상세페이지 리뷰/토크/토크코멘트 CRUD 구현
  client/src/components/Forms/DefalutForm.js
  client/src/components/Forms/TalkForm.js
  client/src/components/Forms/UpdateTalkForm.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/DetailReviewList.js
  client/src/components/Lists/DetailTalkList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/Talk/DetailComment.js
  client/src/components/Lists/MyPageLists/Talk/DetailTalk.js
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Stars/BtnStar.js
  client/src/components/Stars/TextStar.js
  client/src/pages/Detail.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubscriptionOrder.js
Labels: 🐛 fix, ✨ feat, 💄 design, [FE] 김세연, 🚚 rename, 🎨 style

#195 [Client] api연결
  client/.eslintrc.json
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/Price.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/WishListCards.js
  client/src/components/Modals/DefalutModal.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/MypageTab.js
  client/src/components/Tabs/TabButtons.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
  client/src/redux/slice/nickNameSlice.js
Labels: 🐛 fix, 💄 design, [FE] 도현수

#194 [Client] 목록, 검색목록 페이지네이션 구현 외
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Etc/LoadingSpinner.js
  client/src/components/Etc/Pagination.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/ItemList.js
  client/src/pages/Main/Home.js
  client/src/pages/SearchList.js
Labels: 💚 chore, ✨ feat, [FE] 방기현, 🎨 style

#196 [Client] Footer 구현
  client/src/components/Layout/Footer.js
  client/src/components/Layout/LeftNav.js
  client/src/pages/ItemList.js
Labels: ✨ feat, 💄 design, [FE] 안지환

#199 [Server] 서버 마무리 작업
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/login/config/CorsConfig.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/dto/ItemOrderDto.java
  server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
  server/src/main/java/server/team33/subscription/trigger/TriggerService.java
  server/src/main/java/server/team33/talk/dto/TalkAndCommentDto.java
  server/src/main/java/server/team33/talk/mapper/TalkMapper.java
  server/src/main/java/server/team33/wish/dto/WishDto.java
  server/src/main/java/server/team33/wish/mapper/WishMapper.java
  server/src/main/resources/application.yml
Labels: [BE] 김지수, [BE] 김지효, [BE] 최민석

#200 [Client] 장바구니 구매 요청, 타이틀 설정 외
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/components/Etc/Price.js
  client/src/components/Layout/LeftNav.js
  client/src/components/Layout/RightNav.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/ItemList.js
Labels: 🐛 fix, ✨ feat, [FE] 방기현, 🎨 style

#201 [Client] 리다이렉팅 주소 변경 및 오류 수정
  client/src/components/Buttons/BlackButton.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PayDestination.js
  client/src/components/Etc/PayInfo.js
  client/src/components/Etc/PayItemInformation.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.js
  client/src/components/Lists/WishListCards.js
  client/src/components/Tabs/MypageTab.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/SubscriptionOrder.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
  client/src/pages/Payment.js
Labels: 🐛 fix, ✨ feat, [FE] 도현수

#202 [Client] 비회원 안내창 표시, 리뷰/토크 작성자만 수정할 수 있도록 구현 등
  client/src/apis/userApis.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/DetailReviewList.js
  client/src/components/Lists/DetailTalkList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Modals/LoginModal.js
  client/src/components/Modals/WelcomeModal.js
  client/src/hooks/useLogIn.js
  client/src/pages/Detail.js
  client/src/redux/slice/userSlice.js
Labels: 🐛 fix, ✨ feat, [FE] 김세연

#203 [Client] Footer 수정
  client/src/components/Layout/Footer.js
Labels: 💄 design, [FE] 안지환

#204 [Client] 캐러셀 수정, 작성글관리 미작성 안내문구 추가
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Caroucel/Caroucel-Info.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Layout/RightNav.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
Labels: ✨ feat, [FE] 방기현

#205 [Server] 소셜 로그인 시 장바구니 생성, 구독 취소시 itemOrder의 구독 상태 변경
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
  server/src/main/java/server/team33/user/service/UserInfoFilter.java
  server/src/main/java/server/team33/user/service/UserService.java
Labels: 🐛 fix, [BE] 최민석

#206 [Client] 로고 적용 및 이슈 #192 관련 사항 수정
  client/public/favicon.ico
  client/public/index.html
  client/src/assets/Icons.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/Tag.js
  client/src/components/Layout/Footer.js
  client/src/components/Layout/LeftNav.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubscriptionOrder.js
Labels: 🐛 fix, ✨ feat, 💄 design, [FE] 김세연

#208 [Server] 아이템 삭제 기능, 정렬 조건 변겅
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ♻️ refactor, ✨ feat, [BE] 김지수

#210 [Client] 별점 소수점 절삭
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Stars/TextStar.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/Main/Home.js
Labels: ✨ feat, [FE] 방기현, 🎨 style

#212 [Server] 주문 목록 리팩토링
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
Labels: ♻️ refactor, [BE] 김지효

#213 [Server] 여러 상품 정기 구독 시 다음 배송일 출력 수정
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/job/KaKaoSubscriptionJob.java
  server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
Labels: 🐛 fix

#214 [Server] 정기 구독 목록 조회 기능 수정, 일반 결제 요청 헤더 수정
  server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
  server/src/main/java/server/team33/payment/service/PayService.java
Labels: 🐛 fix, [BE] 김지효

#219 [Client] 기타 수정사항(주석제거, api변경에 따른 수정,정기구독관리 페이지)
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/TabButtons.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
Labels: 💄 design, [FE] 도현수, 🎨 style

#218 [Client] RightNav 검색창 수정
  client/src/components/Layout/RightNav.js
Labels: ✨ feat, 💄 design, [FE] 안지환, 🎨 style

#220 [Client] 상세페이지 별점, 정보, 토크 관련 구현 및 수정
  client/src/components/Etc/ItemDetailInfo.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/MainListCard.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Stars/TextStar.js
  client/src/pages/Detail.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/SubscriptionOrder.js
Labels: ✨ feat, 💄 design, [FE] 김세연

#221 [Client] 토스 페이먼츠 버튼 생성
  client/src/components/Etc/PayMethod.js
Labels: ✨ feat, 💄 design, [FE] 도현수

#224 [Server] 구매자임을 확인하는 메서드 리팩토링, 일반 결제 리다이렉팅 주소 수정
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
Labels: ♻️ refactor, [BE] 김지효

#227 [Client] 토크 및 이슈 #192 관련 수정 사항
  client/src/components/Lists/DetailTalkList.js
  client/src/components/Lists/MainListCard.js
  client/src/pages/Detail.js
  client/src/pages/Main/Home.js
Labels: ✨ feat, 💄 design, [FE] 김세연, 🎨 style

#228 [Client] 기타 수정사항
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/Constants.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Lists/WishListCards.js
  client/src/pages/Detail.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubscriptionOrder.js
  client/src/pages/Payment.js
Labels: ♻️ refactor, 💄 design, [FE] 도현수, 🔥remove, 🚚 rename, 🎨 style

#229 [Client] 주석 제거
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Search/Search.js
  client/src/pages/Carts/SubCart.js
Labels: [FE] 안지환, 🎨 style

#236 [Client] axiosinstance 적용, 목록페이지 필터링 UI 리덕스 상태값 연동
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PayMethod.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/DetailTalkList.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/hooks/useFetch.js
  client/src/hooks/usePurchase.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/Detail.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/SubscriptionOrder.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
  client/src/utils/axiosInstance.js
Labels: 🐛 fix, ♻️ refactor, ✨ feat, [FE] 방기현

#238 [Client] 기타 수정사항들
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/Price.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/MainListCard.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/PayList.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Lists/WishListCards.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/Detail.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
Labels: 🐛 fix, ♻️ refactor, ✨ feat, 💄 design, [FE] 도현수, 🔥remove, 🚚 rename, 🎨 style

#240 [Cilent] 메인 브랜치로 merge
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Etc/ItemDetailInfo.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/Price.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Layout/Footer.js
  client/src/components/Lists/DetailTalkList.js
  client/src/components/Lists/MainListCard.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.js
  client/src/components/Lists/PayList.js
  client/src/components/Lists/PayLists.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Lists/WishListCards.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Search/Search.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/hooks/useFetch.js
  client/src/hooks/usePurchase.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/Detail.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/NoteReview.js
  client/src/pages/MyPages/NoteTalk.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/SubscriptionOrder.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
  client/src/utils/axiosInstance.js
Labels: [FE] 도현수, [FE] 김세연, [FE] 방기현, [FE] 안지환

#243 [Client] 상세페이지 리뷰 삭제 구현
  client/src/components/Lists/DetailReviewList.js
Labels: ✨ feat, [FE] 도현수, [FE] 김세연
