Repository codestates-seb/seb40_main_033, pull requests merged in 2022-11, with the labels that each got.

#23 일반 / 정기구독 장바구니 분리, 장바구니 할인 적용
  server/src/main/java/server/team33/cart/controller/CartController.java
  server/src/main/java/server/team33/cart/controller/ItemCartController.java
  server/src/main/java/server/team33/cart/dto/CartResponseDto.java
  server/src/main/java/server/team33/cart/entity/Cart.java
  server/src/main/java/server/team33/cart/mapper/CartMapper.java
  server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
  server/src/main/java/server/team33/cart/repository/ItemCartRepository.java
  server/src/main/java/server/team33/cart/service/CartService.java
  server/src/main/java/server/team33/cart/service/ItemCartService.java
  server/src/main/java/server/team33/response/MultiResponseDto.java
Labels: ✨ feat, [BE] 김지효

#25 Be ms
  server/.idea/.gitignore
  server/.idea/.name
  server/.idea/compiler.xml
  server/.idea/gradle.xml
  server/.idea/jarRepositories.xml
  server/.idea/misc.xml
  server/.idea/vcs.xml
  server/build.gradle
  server/src/main/java/server/team33/audit/Auditable.java
  server/src/main/java/server/team33/cart/entity/ItemCart.java
  server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/exception/controller/ExceptionController.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/details/PrincipalDetails.java
  server/src/main/java/server/team33/login/details/PrincipalDetailsService.java
  server/src/main/java/server/team33/login/dto/LoginDto.java
  server/src/main/java/server/team33/login/filter/JwtLoginFilter.java
  server/src/main/java/server/team33/login/filter/JwtVerificationFilter.java
  server/src/main/java/server/team33/login/handler/UserAccessDeniedHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthFailureHandler.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/login/oauth/Oauth2UserService.java
  server/src/main/java/server/team33/login/oauth/provider/FacebookUserInfo.java
  server/src/main/java/server/team33/login/oauth/provider/GoogleUserInfo.java
  server/src/main/java/server/team33/login/oauth/provider/KakaoUserInfo.java
  server/src/main/java/server/team33/login/oauth/provider/NaverUserInfo.java
  server/src/main/java/server/team33/login/oauth/provider/OAuth2UserInfo.java
  server/src/main/java/server/team33/logout/Logout.java
  server/src/main/java/server/team33/user/controller/UserController.java
  server/src/main/java/server/team33/user/dto/UserDto.java
  server/src/main/java/server/team33/user/dto/UserSignUpDto.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/java/server/team33/user/mapper/UserMapper.java
  server/src/main/java/server/team33/user/redis/RedisConfig.java
  server/src/main/java/server/team33/user/repository/UserRepository.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/test/java/server/team33/user/controller/UserControllerTest.java
  server/src/test/java/server/team33/user/login/jwt/JwtTokenTest.java
  server/src/test/java/server/team33/user/service/UserServiceTest.java
Labels: ✨ feat, [BE] 최민석

#28 💄 design: 버튼 컴포넌트 UI 구현 #19
  client/.eslintrc.json
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/style/GlobalStyle.js
  client/src/assets/style/GlobalVariables.js
  client/src/components/Buttons/DefaultButton.js
  client/src/components/Buttons/LetterButton.js
  client/src/components/Buttons/PurpleButton.js
Labels: 💄 design, [FE] 방기현

#31 [Client] 카운터 버튼 컴포넌트 UI 구현
  client/src/App.js
  client/src/components/Buttons/CounterButton.js
  client/src/components/Header.js
Labels: 💄 design, [FE] 도현수

#32 [Client] 위시리스트버튼 컴포넌트 UI 구현 & gitignore파일 수정
  client/.gitignore
  client/src/components/Buttons/CounterButton.js
  client/src/components/Buttons/WishlistButton.js
  client/src/index.js
Labels: 📝 docs, 💄 design, [FE] 도현수

#34 [Client] 탭 버튼 구현
  client/.gitignore
  client/src/App.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/TabButtons.js
Labels: 💄 design, [FE] 방기현

#35 [Server] 카카오 페이 결제 기능 추가, 일반 결제 기능 추가, 회원 정보 수정 오류 해결, 소셜 로그인 회원 정보 추가 기입 오류 해결
  server/build.gradle
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/exception/controller/ExceptionController.java
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/service/ItemService.java
  server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/login/oauth/Oauth2UserService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/dto/GeneralPayDto.java
  server/src/main/java/server/team33/payment/dto/KakaoPayApproveDto.java
  server/src/main/java/server/team33/payment/dto/KakaoPayRequestDto.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/user/controller/UserController.java
  server/src/main/java/server/team33/user/dto/UserDto.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/java/server/team33/user/entity/UserRoles.java
  server/src/main/java/server/team33/user/repository/UserRepository.java
  server/src/main/java/server/team33/user/service/UserInfoFilter.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/resources/application.yml
  server/src/main/webapp/index.html
  server/src/test/java/server/team33/user/controller/UserControllerTest.java
Labels: 🐛 fix, ♻️ refactor, ✨ feat, [BE] 최민석

#37 [Server] 주문 기능 구현
  server/src/main/java/server/team33/cart/dto/ItemCartDto.java
  server/src/main/java/server/team33/cart/entity/ItemCart.java
  server/src/main/java/server/team33/cart/mapper/CartMapper.java
  server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/dto/ItemOrderDto.java
  server/src/main/java/server/team33/order/dto/OrderDto.java
  server/src/main/java/server/team33/order/entity/ItemOrder.java
  server/src/main/java/server/team33/order/entity/Order.java
  server/src/main/java/server/team33/order/entity/OrderStatus.java
  server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
  server/src/main/java/server/team33/order/mapper/OrderMapper.java
  server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/user/entity/User.java
Labels: ✨ feat, [BE] 김지효

#39 [Client] 태그 버튼 컴포넌트 UI 구현
  client/src/components/Buttons/TagButton.js
Labels: 💄 design, [FE] 도현수

#41 [Client] 왼쪽 Nav 컴포넌트 UI 구현
  client/src/App.js
  client/src/assets/Icons.js
  client/src/components/LeftNav.js
Labels: 💄 design, [FE] 김세연

#44 [Client] 리스트목록 컴포넌트 UI 구현
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Lists/DefaultLIst.js
  client/src/components/Lists/ListCards.js
Labels: 💄 design, [FE] 도현수

#45 [Client] 페이지별 상품목록, 리뷰목록, 검색창 구현 #19
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/assets/style/GlobalStyle.js
  client/src/components/Buttons/CounterButton.js
  client/src/components/Buttons/LetterButton.js
  client/src/components/List/CartList.js
  client/src/components/List/DetailList.js
  client/src/components/List/OrderList.js
  client/src/components/List/PayList.js
  client/src/components/List/Review.js
  client/src/components/List/RewiewForm.js
  client/src/components/RightNav.js
  client/src/components/Search/Search.js
  client/src/components/Talk/Comment.js
  client/src/components/Talk/DetailComment.js
  client/src/components/Talk/DetailTalk.js
  client/src/components/Talk/Talk.js
Labels: 💄 design, [FE] 안지환

#47 [Server] 결제 기능 완성
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/dto/GeneralPayDto.java
  server/src/main/java/server/team33/payment/dto/KakaoPayApproveDto.java
  server/src/main/java/server/team33/payment/dto/KakaoPayRequestDto.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/webapp/index.html
Labels: ✨ feat, [BE] 최민석

#49 [Client] 캐러셀 구현
  client/package-lock.json
  client/package.json
  client/src/components/Buttons/DefaultButton.js
  client/src/components/Buttons/PurpleButton.js
  client/src/components/Caroucel/Caroucel-Info.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Caroucel/slick-theme.css
  client/src/components/Caroucel/slick.css
Labels: 💄 design, [FE] 방기현

#50 [Server] 리뷰 기능 구현
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/dto/OrderDto.java
  server/src/main/java/server/team33/order/mapper/OrderMapper.java
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/review/controller/ReviewController.java
  server/src/main/java/server/team33/review/dto/ReviewDto.java
  server/src/main/java/server/team33/review/dto/ReviewResponseDto.java
  server/src/main/java/server/team33/review/entity/Review.java
  server/src/main/java/server/team33/review/mapper/ReviewMapper.java
  server/src/main/java/server/team33/review/repository/ReviewRepository.java
  server/src/main/java/server/team33/review/service/ReviewService.java
Labels: ✨ feat, [BE] 김지효

#52 [Server] 결제 요청시 상품의 총 개수를 파악할 수 있도록 totalQuantity 필드 추가
  server/src/main/java/server/team33/order/dto/OrderDto.java
  server/src/main/java/server/team33/order/entity/Order.java
  server/src/main/java/server/team33/order/mapper/OrderMapper.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
Labels: ✨ feat, [BE] 김지효

#54 [Server] 카카오페이 결제 시 상품 이름 수정, 일반 로그인 토큰 테스트
  server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/user/controller/UserController.java
  server/src/main/webapp/login.html
Labels: 🐛 fix, [BE] 최민석

#51 [Client] 상세페이지 구매칸 컴포넌트 UI 구현
  client/src/components/Buttons/BlackButton.js
  client/src/components/Buttons/CounterButton.js
  client/src/components/ItemSummary.js/Summary.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/DetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/PayList.js
  client/src/components/Lists/MyPageLists/Review.js
  client/src/components/Lists/MyPageLists/RewiewForm.js
Labels: 💄 design, [FE] 도현수

#57 [Client] 정렬버튼 컴포넌트 UI 구현
  .gitignore
  client/src/components/Buttons/SortButton.js
Labels: 💚 chore, 💄 design, [FE] 도현수

#58 [Client] 회원정보 Input UI 구현
  client/src/assets/style/GlobalStyle.js
  client/src/components/Inputs/AuthInput.js
  client/src/components/Inputs/AuthInputs.js
  client/src/components/Tabs/TabButtons.js
Labels: 💄 design, [FE] 방기현

#59 [Client] 가격정렬 버튼 컴포넌트 UI 구현
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortAndSearchButtons.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/ItemSummary.js/Summary.js
Labels: 💄 design, [FE] 도현수

#62 [Client] 페이지네이션 컴포넌트 UI 구현
  client/src/components/ItemSummary.js/Summary.js
  client/src/components/Pagination.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/TabButtons.js
Labels: 💄 design, [FE] 도현수

#61 [Server] 카테고리 기능 수정, 브랜드 클래스 추가
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/category/entity/Category.java
  server/src/main/java/server/team33/category/entity/ItemCategory.java
  server/src/main/java/server/team33/exception/controller/ExceptionController.java
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
  server/src/main/java/server/team33/item/entity/Brand.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
Labels: 🐛 fix, [BE] 김지수, 🔥remove

#64 [Client] 모달, 폼 컴포넌트 UI 구현
  client/package-lock.json
  client/package.json
  client/src/components/Buttons/PurpleButton.js
  client/src/components/Etc/PageTitle.js
  client/src/components/Etc/Price.js
  client/src/components/Etc/RecommendedTitle.js
  client/src/components/Forms/DefalutForm.js
  client/src/components/Forms/ReviewForm.js
  client/src/components/Forms/TalkForm.js
  client/src/components/Forms/UpdateTalkForm.js
  client/src/components/LeftNav.js
  client/src/components/Modals/DefalutModal.js
  client/src/components/Modals/DeleteAccountModal.js
  client/src/components/Modals/GoodbyeModal.js
  client/src/components/Modals/OrderCompleteModal.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Modals/WelcomeModal.js
  client/src/components/Modals/style.css
  client/src/components/Stars/BtnStar.js
  client/src/components/Stars/TextStar.js
Labels: 💄 design, [FE] 김세연

#69 [Server] 카테고리별 아이템 조회 기능 수정
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: 🐛 fix, [BE] 김지효

#70 [Server] Talk & TalkComment 기능 구현
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/talk/controller/TalkCommentController.java
  server/src/main/java/server/team33/talk/controller/TalkController.java
  server/src/main/java/server/team33/talk/dto/TalkAndCommentDto.java
  server/src/main/java/server/team33/talk/dto/TalkCommentDto.java
  server/src/main/java/server/team33/talk/dto/TalkDetailResponseDto.java
  server/src/main/java/server/team33/talk/dto/TalkDto.java
  server/src/main/java/server/team33/talk/dto/TalkOrCommentDto.java
  server/src/main/java/server/team33/talk/dto/TalkResponseDto.java
  server/src/main/java/server/team33/talk/entity/Talk.java
  server/src/main/java/server/team33/talk/entity/TalkComment.java
  server/src/main/java/server/team33/talk/mapper/TalkMapper.java
  server/src/main/java/server/team33/talk/repository/TalkCommentRepository.java
  server/src/main/java/server/team33/talk/repository/TalkRepository.java
  server/src/main/java/server/team33/talk/service/TalkCommentService.java
  server/src/main/java/server/team33/talk/service/TalkService.java
Labels: ✨ feat, [BE] 김지효

#71 [Client] 상하단 margin 추가 및 Nav sticky 추가
  client/.gitignore
  client/src/components/Layout/Layout.js
  client/src/components/Layout/LeftNav.js
  client/src/components/Layout/RightNav.js
  client/src/index.js
Labels: 💄 design, [FE] 김세연

#73 [Client] border 삭제&수정, 폰트 수정
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/DetailReviewList.js
  client/src/components/Lists/MyPageLists/MyPageReviewList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/PayList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Talk/Comment.js
  client/src/components/Talk/DetailComment.js
  client/src/components/Talk/DetailTalk.js
  client/src/components/Talk/Talk.js
Labels: 💄 design, [FE] 안지환

#76 [Server] 정기 구독 기능 구현 1.0
  server/src/main/java/server/team33/exception/bussiness/ExceptionCode.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/entity/ItemOrder.java
  server/src/main/java/server/team33/order/reposiroty/ItemOrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/scheduler/config/Config.java
  server/src/main/java/server/team33/scheduler/controller/SchedualingController.java
  server/src/main/java/server/team33/scheduler/service/SchedulingService.java
  server/src/main/java/server/team33/scheduler/service/SubscriptionService.java
Labels: ✨ feat, [BE] 최민석

#80 [Server] 카테고리별 브랜드별 모아보기 기능
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/category/entity/Category.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/BrandService.java
  server/src/main/java/server/team33/item/service/ItemService.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/java/server/team33/wish/controller/WishController.java
  server/src/main/java/server/team33/wish/dto/WishResponseDto.java
  server/src/main/java/server/team33/wish/entity/Wish.java
  server/src/main/java/server/team33/wish/mapper/WishMapper.java
  server/src/main/java/server/team33/wish/repository/WishRepository.java
  server/src/main/java/server/team33/wish/service/WishService.java
Labels: ✨ feat, [BE] 김지수

#81 [Client] 배경 색 path별로 분기 설정 및 마이페이지 Header 구현
  client/src/components/Buttons/LetterButton.js
  client/src/components/Etc/MyPageHeader.js
  client/src/components/Etc/PageTitle.js
  client/src/components/Layout/Layout.js
  client/src/pages/MyPage.js
Labels: 💄 design, [FE] 김세연

#87 [Server] 장바구니 일부 및 전체 목록 주문 기능 구현
  server/src/main/java/server/team33/cart/controller/CartController.java
  server/src/main/java/server/team33/cart/controller/ItemCartController.java
  server/src/main/java/server/team33/cart/dto/CartResponseDto.java
  server/src/main/java/server/team33/cart/dto/ItemCartDto.java
  server/src/main/java/server/team33/cart/entity/Cart.java
  server/src/main/java/server/team33/cart/entity/ItemCart.java
  server/src/main/java/server/team33/cart/mapper/CartMapper.java
  server/src/main/java/server/team33/cart/mapper/ItemCartMapper.java
  server/src/main/java/server/team33/cart/repository/ItemCartRepository.java
  server/src/main/java/server/team33/cart/service/CartService.java
  server/src/main/java/server/team33/cart/service/ItemCartService.java
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/mapper/ItemOrderMapper.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/user/service/UserService.java
Labels: ♻️ refactor, ✨ feat, [BE] 김지효

#91 [Server] 할인 모아보기 기능 구현
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지수

#92 [Client] 카카오 주소 api 연결 및 모달 구현
  client/package-lock.json
  client/package.json
  client/src/components/ItemSummary/Summary.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/DefaultList.js
  client/src/components/Modals/AddressModal.js
  client/src/components/Modals/DefalutModal.js
  client/src/components/Modals/DeleteAccountModal.js
  client/src/components/Modals/GoodbyeModal.js
  client/src/components/Tabs/MypageTab.js
  client/src/pages/MyPages/UserInfo.js
Labels: 💚 chore, 💄 design, [FE] 도현수

#93 [Client] 가격 및 날짜 컴포넌트 구현
  client/package-lock.json
  client/package.json
  client/src/components/Buttons/DefaultButton.js
  client/src/components/Buttons/LetterButton.js
  client/src/components/Etc/ListDate.js
  client/src/components/Etc/Price.js
  client/src/components/Lists/MyPageLists/DetailReviewList.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Lists/MyPageLists/PayList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Tabs/MypageTab.js
Labels: 💚 chore, ✨ feat, 💄 design, [FE] 김세연

#94 [Server] detailAddress 필드 및 mapper, dto 추가
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/scheduler/config/Config.java
  server/src/main/java/server/team33/scheduler/controller/SchedulingController.java
  server/src/main/java/server/team33/scheduler/service/SchedulingService.java
  server/src/main/java/server/team33/scheduler/service/SubscriptionService.java
  server/src/main/java/server/team33/user/dto/UserDto.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/java/server/team33/user/mapper/UserMapper.java
  server/src/main/java/server/team33/user/service/UserService.java
Labels: ✨ feat, [BE] 최민석

#96 [Client] 회원가입 페이지 구현중
  client/.eslintrc.json
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Etc/AuthTitle.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/Inputs/AuthInput.js
  client/src/components/Inputs/AuthInputs.js
  client/src/components/Layout/Layout.js
  client/src/pages/SignUp.js
Labels: ✨ feat, 💄 design, [FE] 방기현

#97 [Server] 아이템 판매량 집계, 아이템의 리뷰 및 토크 목록 불러오기
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/dto/OrderDto.java
  server/src/main/java/server/team33/order/entity/Order.java
  server/src/main/java/server/team33/order/mapper/OrderMapper.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/review/repository/ReviewRepository.java
  server/src/main/java/server/team33/review/service/ReviewService.java
  server/src/main/java/server/team33/talk/mapper/TalkMapper.java
  server/src/main/java/server/team33/talk/repository/TalkRepository.java
  server/src/main/java/server/team33/talk/service/TalkService.java
Labels: ✨ feat, [BE] 김지효

#99 [Client] 회원가입 페이지 주소 라이브러리 연결 외
  client/src/components/Buttons/DefaultButton.js
  client/src/components/Buttons/PurpleButton.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/Inputs/AuthInput.js
  client/src/pages/SignUp.js
Labels: ✨ feat, [FE] 방기현

#102 [Client] 상품 목록 구현, 검색 목록 페이지 UI 보완
  client/.gitignore
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/SmallListCards.js
  client/src/components/Search/Search.js
  client/src/pages/ItemList.js
  client/src/pages/NormalCart.js
  client/src/pages/SearchList.js
  client/src/pages/SubCart.js
Labels: ✨ feat, 💄 design, [FE] 안지환

#103 :sparkles: feat: 로그인한 회원의 찜하기 기능 구현
  server/src/main/java/server/team33/item/entity/Item.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/wish/controller/WishController.java
  server/src/main/java/server/team33/wish/dto/WishResponseDto.java
  server/src/main/java/server/team33/wish/entity/Wish.java
  server/src/main/java/server/team33/wish/mapper/WishMapper.java
  server/src/main/java/server/team33/wish/repository/WishRepository.java
  server/src/main/java/server/team33/wish/service/WishService.java
Labels: ✨ feat, [BE] 김지수

#104 [Server] 정기 구독 기능 재구현
  server/build.gradle
  server/src/main/java/server/team33/order/entity/ItemOrder.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/scheduler/config/Config.java
  server/src/main/java/server/team33/scheduler/controller/SchedulingController.java
  server/src/main/java/server/team33/scheduler/service/SchedulingService.java
  server/src/main/java/server/team33/scheduler/service/SubscriptionService.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/job/JobDetailService.java
  server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
  server/src/main/java/server/team33/subscription/trigger/TriggerService.java
  server/src/main/resources/application.yml
  server/src/test/java/server/team33/user/controller/UserControllerTest.java
Labels: ✨ feat, [BE] 최민석

#105 :sparkles: feat: 로그인한 회원의 찜한 상품 목록 불러오기
  server/src/main/java/server/team33/wish/controller/WishController.java
  server/src/main/java/server/team33/wish/dto/WishDto.java
  server/src/main/java/server/team33/wish/dto/WishResponseDto.java
  server/src/main/java/server/team33/wish/mapper/WishMapper.java
  server/src/main/java/server/team33/wish/repository/WishRepository.java
  server/src/main/java/server/team33/wish/service/WishService.java
Labels: ✨ feat, [BE] 김지수

#107 [Client] 마이페이지-회원정보수정 페이지 목데이터 구현
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/ItemSummary/Summary.js
  client/src/pages/MyPages/UserInfo.js
Labels: ✨ feat, 💄 design, [FE] 도현수

#109 [Client] 주문내역 상세 페이지 UI 구현
  client/src/Router.js
  client/src/components/Etc/PayInfo.js
  client/src/components/Etc/Price.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Lists/MyPageLists/OrderList.js
  client/src/components/Tabs/MypageTab.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubscriptionOrder.js
Labels: ✨ feat, 💄 design, [FE] 김세연

#112 [Client] 로그인, 회원가입 페이지, 메인 캐러셀 UI 구현
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Caroucel/slick-theme.css
  client/src/components/Inputs/AuthForm.js
  client/src/components/Inputs/AuthInput.js
  client/src/components/Layout/Layout.js
  client/src/components/Modals/AddressModal.js
  client/src/pages/Home.js
  client/src/pages/LogIn.js
  client/src/pages/SignUp.js
Labels: 🐛 fix, ✨ feat, 💄 design, [FE] 방기현

#113 [Server] 메인페이지에서 best 상품, sale 상품 9개씩 조회하기
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지수

#114 [Server] 아이템 키워드 검색 및 가격 필터링 기능 구현
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지효

#123 [Client] 카드캐러셀, 소셜로그인 구현 + 라이브러리 세팅
  client/src/App.js
  client/src/Router.js
  client/src/apis/login.js
  client/src/assets/images/background.png
  client/src/assets/images/social/google.svg
  client/src/assets/images/social/kakao.png
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Caroucel/slick-theme.css
  client/src/components/Etc/RecommendedTitle.js
  client/src/components/Inputs/AuthForm.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/Auth/SocialLogin.js
  client/src/pages/Home.js
  client/src/pages/Main/Home.js
  client/src/pages/Main/MainSection.js
  client/src/redux/slice/userSlice.js
  client/src/redux/store/store.js
  client/src/utils/axiosInstance.js
Labels: 🐛 fix, ✨ feat, 💄 design, [FE] 방기현, 🚚 rename, 🎨 style

#124 [Client] 리뷰 모달 연결, 장바구니 페이지 라우팅 중첩, 가격필터 CSS 수정 외
  client/src/Router.js
  client/src/components/Buttons/PurpleButton.js
  client/src/components/Buttons/SearchButtons/PriceButton.js
  client/src/components/Buttons/SearchButtons/SortAndSearchButtons.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Etc/PageTitle.js
  client/src/components/Forms/DefalutForm.js
  client/src/components/Layout/RightNav.js
  client/src/components/Lists/MyPageLists/OrderDetailList.js
  client/src/components/Modals/DefalutModal.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Stars/BtnStar.js
  client/src/components/Tabs/DefaultTabButton.js
  client/src/components/Tabs/MypageTab.js
  client/src/components/Tabs/TabButtons.js
  client/src/pages/Cart.js
  client/src/pages/MyPage.js
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/MyPages/SubscriptionOrder.js
Labels: 🐛 fix, ♻️ refactor, ✨ feat, 💄 design, [FE] 김세연

#125 [Server] 영양성분 등록하기 기능 구현
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/nutritionFact/dto/NutritionFactDto.java
Labels: ✨ feat, [BE] 김지수

#127 [Server] 아이템 키워드검색 결과 필터링 중첩 적용
  server/src/main/java/server/team33/item/controller/ItemController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지효

#129 [Server] 기능별 카테고리 기능 중첩 적용
  server/src/main/java/server/team33/category/controller/CategoryController.java
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/repository/ItemRepository.java
  server/src/main/java/server/team33/item/service/ItemService.java
Labels: ✨ feat, [BE] 김지수

#132 [Client] 상세 페이지 UI 구현 및 관련 컴포넌트 수정
  client/src/components/Buttons/TagButton.js
  client/src/components/Buttons/WishlistButton.js
  client/src/components/Etc/Tag.js
  client/src/components/Forms/DefalutForm.js
  client/src/components/Forms/ReviewForm.js
  client/src/components/Forms/TalkForm.js
  client/src/components/ItemSummary/Summary.js
  client/src/components/Lists/DetailReviewList.js
  client/src/components/Lists/MyPageLists/DetailReviewList.js
  client/src/components/Stars/TextStar.js
  client/src/pages/Detail.js
Labels: 💄 design, [FE] 김세연, 🚚 rename, 🎨 style

#131 [Client] 상품 목록 페이지& 장바구니 페이지 구현
  client/src/Router.js
  client/src/components/Buttons/SearchButtons/SortButton.js
  client/src/components/Categories/Categories.js
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/SmallListCards.js
  client/src/pages/Cart.js
  client/src/pages/Carts/NormalCart.js
  client/src/pages/Carts/SubCart.js
  client/src/pages/ItemList.js
  client/src/pages/SearchList.js
Labels: ✨ feat, 💄 design, [FE] 안지환, 🚚 rename

#133 [Client] 결제 페이지 UI 구현 중간단계
  client/.gitignore
  client/src/App.js
  client/src/Router.js
  client/src/components/Etc/FinalPaymentInfomation.js
  client/src/components/Etc/PayDestination.js
  client/src/components/Etc/PayItemInformation.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/PayPageContainer.js
  client/src/components/Etc/PaymentInfoMethod.js
  client/src/components/Etc/Price.js
  client/src/components/Lists/PayList.js
  client/src/components/Lists/PayLists.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/Payment.js
Labels: ✨ feat, 💄 design, [FE] 도현수, 🚚 rename, 🎨 style

#134 [Client] 로그인, 메인 캐러셀 변경
  client/src/apis/login.js
  client/src/components/Caroucel/CardCaroucel.js
  client/src/components/Caroucel/MainCaroucel.js
  client/src/components/Etc/RecommendedTitle.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/Inputs/AuthInput.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/Auth/SocialLogin.js
  client/src/pages/Main/Home.js
  client/src/pages/Main/MainSection.js
  client/src/redux/slice/userSlice.js
Labels: 💄 design, [FE] 방기현, 🎨 style

#135 Be ms
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/login/oauth/Oauth2UserService.java
  server/src/main/java/server/team33/order/entity/ItemOrder.java
  server/src/main/java/server/team33/order/entity/Order.java
  server/src/main/java/server/team33/order/entity/OrderStatus.java
  server/src/main/java/server/team33/order/service/ItemOrderService.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/service/PayService.java
  server/src/main/java/server/team33/payment/service/SubsPayService.java
  server/src/main/java/server/team33/subscription/controller/ScheduleController.java
  server/src/main/java/server/team33/subscription/job/JobDetailService.java
  server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
  server/src/main/java/server/team33/subscription/service/SubscriptionService.java
  server/src/main/java/server/team33/subscription/trigger/TriggerService.java
  server/src/main/java/server/team33/user/controller/UserController.java
  server/src/main/java/server/team33/user/dto/UserDto.java
  server/src/main/java/server/team33/user/entity/User.java
  server/src/main/java/server/team33/user/service/UserService.java
  server/src/main/webapp/subs.html
Labels: ✨ feat, [BE] 최민석

#139 [Client] 회원가입/로그인 페이지 API 통신+useFetch 구현
  client/package-lock.json
  client/package.json
  client/src/App.js
  client/src/apis/userApis.js
  client/src/components/Inputs/AuthForm.js
  client/src/hooks/useFetch.js
  client/src/hooks/useLogin.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/Auth/SocialLogin.js
  client/src/pages/MyPages/UserInfo.js
  client/src/redux/slice/userSlice.js
  client/src/redux/store/store.js
  client/src/utils/axiosInstance.js
Labels: ♻️ refactor, ✨ feat, [FE] 도현수, [FE] 방기현, 🚚 rename, 🎨 style

#141 [Client] 결제페이지 UI 구현과 기타 수정사항들
  client/package-lock.json
  client/package.json
  client/src/components/Etc/DefaultPayment.js
  client/src/components/Etc/FinalPaymentInfomation.js
  client/src/components/Etc/PayDestination.js
  client/src/components/Etc/PayItemInformation.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/PayPageContainer.js
  client/src/components/Etc/PaymentInfoMethod.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Lists/PayLists.js
  client/src/components/Modals/DeleteAccountModal.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
  client/src/pages/MyPages/WishList.js
  client/src/pages/Payment.js
  client/src/pages/SubPayment.js
Labels: 💚 chore, ✨ feat, 💄 design, [FE] 도현수, 🚚 rename, 🎨 style

#142 [Server] 일반 로그인시 토큰 발행 위치 수정, 회원 정보 조회 시 소셜 로그인한 회원 구분
  server/src/main/java/server/team33/login/config/CustomFilterConfigurer.java
  server/src/main/java/server/team33/login/config/SecurityConfig.java
  server/src/main/java/server/team33/login/filter/JwtLoginFilter.java
  server/src/main/java/server/team33/login/handler/UserAuthSuccessHandler.java
  server/src/main/java/server/team33/payment/contoller/PaymentController.java
  server/src/main/java/server/team33/payment/dto/KakaoPayApproveDto.java
  server/src/main/java/server/team33/payment/service/SubsPayService.java
  server/src/main/java/server/team33/subscription/job/SubscriptionJob.java
  server/src/main/java/server/team33/user/controller/UserController.java
  server/src/main/java/server/team33/user/dto/UserDto.java
  server/src/main/java/server/team33/user/mapper/UserMapper.java
  server/src/main/java/server/team33/user/service/UserService.java
Labels: 🐛 fix, ✨ feat, [BE] 최민석

#145 [Server] 정기 구독 목록 조회 기능 구현, 위시 리스트 조회 기능 수정
  server/src/main/java/server/team33/item/dto/ItemDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
  server/src/main/java/server/team33/order/controller/OrderController.java
  server/src/main/java/server/team33/order/reposiroty/OrderRepository.java
  server/src/main/java/server/team33/order/service/OrderService.java
  server/src/main/java/server/team33/wish/controller/WishController.java
  server/src/main/java/server/team33/wish/dto/WishDto.java
  server/src/main/java/server/team33/wish/mapper/WishMapper.java
  server/src/main/java/server/team33/wish/repository/WishRepository.java
  server/src/main/java/server/team33/wish/service/WishService.java
Labels: 🐛 fix, ✨ feat, [BE] 김지효

#148 [Client] useFetch CRUD Hooks 구현
  client/src/App.js
  client/src/apis/userApis.js
  client/src/components/Inputs/AuthForm.js
  client/src/components/Inputs/AuthInput.js
  client/src/hooks/useFetch.js
  client/src/hooks/useLogIn.js
  client/src/pages/Auth/LogIn.js
  client/src/pages/Auth/SignUp.js
  client/src/pages/Main/Home.js
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/UserInfo.js
  client/src/redux/slice/userSlice.js
  client/src/utils/axiosInstance.js
Labels: ✨ feat, [FE] 도현수, [FE] 방기현, 🎨 style

#151 [Client] Nav 페이지 이동 구현 및 페이지 이동 시 스크롤 최상단에 위치하도록 구현
  client/src/Router.js
  client/src/components/Layout/LeftNav.js
  client/src/components/Layout/RightNav.js
  client/src/utils/ScrollToTop.js
Labels: ✨ feat, [FE] 김세연
