Repository codestates-seb/seb40_main_033, pull requests merged in 2023-04, with the labels that each got.

#294 [Client] 마이페이지 - 주문내역 조회 (일반/정기) 무한스크롤 적용
  client/src/apis/itemApis.ts
  client/src/components/Etc/Constants.js
  client/src/hooks/useGetList.ts
  client/src/pages/MyPages/NormalOrder.js
  client/src/pages/MyPages/SubscriptionOrder.js
  client/src/types/order.type.ts
Labels: ✨ feat, [FE] 김세연

#297 [Client] useGet에 제네릭 적용 및 403 에러 처리
  client/src/components/Etc/Constants.js
  client/src/hooks/useFetch.ts
Labels: ✨ feat, [FE] 김세연

#300 [Client] 타입스크립트 리팩터링 - 주문내역 조회(일반/정기), 주문내역 상세조회 외
  client/src/App.tsx
  client/src/apis/itemApis.ts
  client/src/components/Buttons/WishlistButton.tsx
  client/src/components/ItemSummary/ItemSummary.tsx
  client/src/components/Lists/MyPageLists/OrderDetailList.tsx
  client/src/components/Lists/MyPageLists/OrderList.tsx
  client/src/hooks/useGetWishes.ts
  client/src/pages/Detail.tsx
  client/src/pages/MyPages/NormalOrder.tsx
  client/src/pages/MyPages/OrderDetail.tsx
  client/src/pages/MyPages/SubscriptionOrder.tsx
  client/src/types/button.type.ts
  client/src/types/itemList.type.ts
  client/src/types/order.type.ts
Labels: 🐛 fix, ♻️ refactor, ✨ feat, [FE] 김세연

#305 [Client] 타입스크립트 리팩터링 - DefaultModal
  client/src/components/Etc/PayMethod.tsx
  client/src/components/Inputs/AuthForm.tsx
  client/src/components/ItemSummary/ItemSummary.tsx
  client/src/components/Lists/DetailReviewList.tsx
  client/src/components/Lists/DetailTalkList.tsx
  client/src/components/Lists/MyPageLists/CartList.tsx
  client/src/components/Lists/MyPageLists/MyPageReviewList.tsx
  client/src/components/Lists/MyPageLists/OrderDetailList.tsx
  client/src/components/Lists/MyPageLists/OrderList.tsx
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.tsx
  client/src/components/Modals/AddressModal.js
  client/src/components/Modals/CancelModal.js
  client/src/components/Modals/CartModal.js
  client/src/components/Modals/DefalutModal.js
  client/src/components/Modals/DeleteAccountModal.js
  client/src/components/Modals/DeleteNotesModal.js
  client/src/components/Modals/GoodbyeModal.js
  client/src/components/Modals/LoginModal.js
  client/src/components/Modals/OrderCompleteModal.js
  client/src/components/Modals/ReviewModal.js
  client/src/components/Modals/TalkModal.js
  client/src/components/Modals/style.css
  client/src/pages/MyPages/OrderDetail.tsx
  client/src/pages/MyPages/UserInfo.js
  client/src/types/modal.type.ts
Labels: 🐛 fix, ♻️ refactor, 💄 design, [FE] 김세연

#307 [Client] 타입스크립트 리팩터링 - Modal, Constants.js 파일 경로 변경 외
  client/src/assets/Constants.ts
  client/src/assets/constants/MainCaroucel-Info.ts
  client/src/components/Caroucel/MainCaroucel.tsx
  client/src/components/Etc/Constants.js
  client/src/components/Etc/DetailProductInfo.tsx
  client/src/components/Etc/ListDate.tsx
  client/src/components/Etc/MyPageHeader.tsx
  client/src/components/Etc/PayItemInformation.tsx
  client/src/components/Etc/PayMethod.tsx
  client/src/components/Etc/Tag.tsx
  client/src/components/ItemSummary/ItemSummary.tsx
  client/src/components/Layout/Footer.tsx
  client/src/components/Layout/LeftNav.tsx
  client/src/components/Lists/CartList.tsx
  client/src/components/Lists/DetailReviewList.tsx
  client/src/components/Lists/DetailTalkList.tsx
  client/src/components/Lists/MyPageLists/MyPageReviewList.tsx
  client/src/components/Lists/MyPageLists/MyPageTalkList.tsx
  client/src/components/Lists/MyPageLists/OrderDetailList.tsx
  client/src/components/Lists/MyPageLists/OrderList.tsx
  client/src/components/Lists/MyPageLists/Talk/DetailComment.js
  client/src/components/Lists/MyPageLists/Talk/DetailTalk.js
  client/src/components/Lists/ShoppingList.tsx
  client/src/components/Modals/AddressModal.tsx
  client/src/components/Modals/CancelModal.tsx
  client/src/components/Modals/CartModal.tsx
  client/src/components/Modals/DefalutModal.tsx
  client/src/components/Modals/DeleteAccountModal.tsx
  client/src/components/Modals/DeleteNotesModal.js
  client/src/components/Modals/DeleteNotesModal.tsx
  client/src/components/Modals/GoodbyeModal.tsx
  client/src/components/Modals/LoginModal.js
  client/src/components/Modals/LoginModal.tsx
  client/src/components/Modals/OrderCompleteModal.js
  client/src/components/Modals/ReviewModal.tsx
  client/src/components/Modals/TalkModal.tsx
  client/src/components/Tabs/MypageTab.tsx
  client/src/hooks/useFetch.ts
  client/src/pages/Carts/NormalCart.tsx
  client/src/pages/Carts/SubCart.tsx
  client/src/pages/Detail.tsx
  client/src/pages/MyPages/NormalOrder.tsx
  client/src/pages/MyPages/NoteReview.tsx
  client/src/pages/MyPages/NoteTalk.tsx
  client/src/pages/MyPages/OrderDetail.tsx
  client/src/pages/MyPages/SubManage.js
  client/src/pages/MyPages/SubscriptionOrder.tsx
  client/src/pages/MyPages/WishList.js
  client/src/types/item.type.ts
  client/src/types/modal.type.ts
  client/src/types/note.type.ts
  client/src/types/order.type.ts
Labels: ♻️ refactor, ✨ feat, [FE] 김세연, 🔥remove, 🚚 rename

#304 [Client] esbuild 도입으로 빌드 성능 개선 외
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/utils/axiosInstance.ts
  client/tsconfig.json
Labels: ♻️ refactor

#310 [Client] EsbuildPlugin 적용하여 빌드 파일 용량 축소
  client/craco.config.js
  client/package-lock.json
  client/package.json
  client/src/assets/Constants.ts
  client/src/components/Etc/PayMethod.tsx
  client/src/hooks/useFetch.ts
  client/src/pages/Auth/SocialLogIn.tsx
Labels: ♻️ refactor, [FE] 김세연

#312 [Client] 타입스크립트 리팩터링 - 정기구독관리 및 위시리스트
  client/src/Router.tsx
  client/src/assets/Constants.ts
  client/src/components/Lists/MyPageLists/SubManagementList.tsx
  client/src/pages/MyPages/SubscriptionManagement.tsx
  client/src/pages/MyPages/WishList.tsx
  client/src/types/order.type.ts
Labels: ♻️ refactor

#315 [Client] 타입스크립트 리팩터링 - 유저정보조회
  client/src/Router.tsx
  client/src/pages/MyPages/UserProfile.tsx
Labels: ♻️ refactor
