Repository codestates-seb/seb40_main_033, pull requests merged in 2023-03, with the labels that each got.

#268 [Client] 타입스크립트 리팩터링 - Main 페이지, 케러셀
  client/src/assets/constants/MainCaroucel-Info.ts
  client/src/components/Caroucel/CardCaroucel.tsx
  client/src/components/Caroucel/Caroucel-Info.tsx
  client/src/components/Caroucel/MainCaroucel.tsx
  client/src/types/main.type.ts
Labels: ♻️ refactor, [FE] 방기현, 🚚 rename

#274 [Client] 타입스크립트 리팩터링 - ItemCard
  client/src/components/Cards/ItemCard.tsx
  client/src/components/Cards/MainListCard.tsx
  client/src/components/Cards/SmallListCard.tsx
  client/src/components/Cards/WishListCard.tsx
  client/src/components/Caroucel/CardCaroucel.tsx
  client/src/components/Forms/DefalutForm.tsx
  client/src/components/Forms/TalkForm.tsx
  client/src/components/Lists/MainListCard.tsx
  client/src/components/Lists/WishListCards.js
  client/src/pages/ItemList.tsx
  client/src/pages/Main/MainSection.tsx
  client/src/pages/MyPages/WishList.js
  client/src/pages/SearchList.tsx
  client/src/types/button.type.ts
  client/src/types/form.type.ts
  client/src/types/main.type.ts
Labels: ♻️ refactor, [FE] 도현수

#276 [Client] 타입스크립트 리팩터링 - 로그인, 회원가입 페이지
  client/src/apis/itemApis.ts
  client/src/apis/userApis.ts
  client/src/components/Caroucel/CardCaroucel.tsx
  client/src/components/Caroucel/Caroucel-Info.tsx
  client/src/components/Caroucel/MainCaroucel.tsx
  client/src/components/Etc/Price.tsx
  client/src/components/Inputs/AuthForm.tsx
  client/src/components/Inputs/AuthInput.tsx
  client/src/hooks/useGetList.tsx
  client/src/hooks/useLogIn.tsx
  client/src/pages/Auth/LogIn.tsx
  client/src/pages/Auth/SignUp.tsx
  client/src/pages/Auth/SocialLogIn.tsx
  client/src/pages/Main/Home.tsx
  client/src/types/auth.type.ts
  client/src/types/itemList.type.ts
  client/src/types/main.type.ts
  client/src/types/price.type.ts
  client/src/utils/typePredicates.ts
Labels: ♻️ refactor, [FE] 방기현, 🚚 rename

#279 [Client] 타입스크립트 리팩터링 - useFetch, usePurchase
  client/src/components/Caroucel/CardCaroucel.tsx
  client/src/components/Etc/Price.tsx
  client/src/hooks/useFetch.tsx
  client/src/hooks/usePurchase.tsx
  client/src/types/button.type.ts
  client/src/types/price.type.ts
Labels: 🐛 fix, ♻️ refactor, [FE] 김세연

#282 [Client] 타입스크립트 리팩터링 - 장바구니 페이지
  client/src/components/Lists/MyPageLists/CartList.tsx
  client/src/hooks/useLogIn.ts
  client/src/hooks/usePurchase.tsx
  client/src/pages/Cart.tsx
  client/src/pages/Carts/NormalCart.tsx
  client/src/pages/Carts/SubCart.tsx
  client/src/pages/Main/Home.tsx
  client/src/pages/NotFound.tsx
  client/src/types/cart.type.ts
  client/src/types/main.type.ts
Labels: 🐛 fix, ♻️ refactor, [FE] 방기현

#284 [Client] 타입스크립트 리팩터링 - 장바구니 페이지
  client/src/components/Lists/MyPageLists/MyPageReviewList.tsx
  client/src/components/Lists/MyPageLists/Talk/MyPageTalk.tsx
  client/src/pages/MyPages/NoteReview.tsx
  client/src/pages/MyPages/NoteTalk.tsx
  client/src/types/note.type.ts
Labels: ♻️ refactor, [FE] 방기현

#286 [Client] 타입스크립트 리팩터링 - 결제 페이지
  client/src/Router.tsx
  client/src/components/Etc/CustomerInformation.tsx
  client/src/components/Etc/DefaultPaymentForm.tsx
  client/src/components/Etc/FinalPaymentInfomation.js
  client/src/components/Etc/PayItemInformation.tsx
  client/src/components/Etc/PayMethod.tsx
  client/src/components/Etc/PayPageContainer.tsx
  client/src/components/Etc/PaymentSummary.tsx
  client/src/components/Lists/ShoppingList.tsx
  client/src/components/Modals/TalkModal.js
  client/src/pages/MyPages/OrderDetail.js
  client/src/pages/Payment.js
  client/src/pages/Payment.tsx
  client/src/pages/SubPayment.js
  client/src/pages/SubscriptionPayment.tsx
  client/src/types/cart.type.ts
  client/src/types/item.type.ts
  client/src/types/itemList.type.ts
  client/src/types/note.type.ts
  client/src/types/payment.type.ts
Labels: ♻️ refactor, [FE] 도현수, 🚚 rename

#288 [Server] ItemSimpleResponseDto 의 필드 수정
  server/src/main/java/server/team33/item/dto/ItemSimpleResponseDto.java
  server/src/main/java/server/team33/item/mapper/ItemMapper.java
Labels: ♻️ refactor, [BE] 김지효

#291 [Client] 타입스크립트 리팩터링 - 상세 페이지, disCountPrice ⇒ discountPrice 변경, 장바구니 에러 수정 외
  client/public/index.html
  client/src/components/Etc/PayItemInformation.tsx
  client/src/components/ItemSummary/ItemSummary.tsx
  client/src/components/Lists/DetailReviewList.tsx
  client/src/components/Lists/DetailTalkList.tsx
  client/src/components/Lists/MyPageLists/CartList.tsx
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Modals/TalkModal.js
  client/src/pages/Carts/SubCart.tsx
  client/src/pages/Detail.tsx
  client/src/pages/MyPages/NoteReview.tsx
  client/src/pages/MyPages/OrderDetail.js
  client/src/types/form.type.ts
  client/src/types/item.type.ts
  client/src/types/itemList.type.ts
  client/src/types/main.type.ts
  client/src/types/note.type.ts
Labels: 🐛 fix, ♻️ refactor, ✨ feat, [FE] 김세연
