Repository codestates-seb/seb40_main_033, pull requests merged in 2023-02, with the labels that each got.

#256 [Client] 타입스크립트 리팩터링 - Stars
  client/.eslintrc.json
  client/src/components/Stars/BtnStar.tsx
  client/src/components/Stars/TextStar.tsx
Labels: ♻️ refactor, 📝 docs, [FE] 도현수

#259 [Client] 타입스크립트 리팩터링 - ItemList, utils 외
  client/src/apis/itemApis.ts
  client/src/components/Buttons/BlackButton.tsx
  client/src/components/Buttons/CounterButton.tsx
  client/src/components/Buttons/DefaultButton.tsx
  client/src/components/Buttons/LetterButton.tsx
  client/src/components/Buttons/PurpleButton.tsx
  client/src/components/Buttons/SearchButtons/PriceButton.tsx
  client/src/components/Buttons/WishlistButton.tsx
  client/src/components/Etc/LoadingSpinner.tsx
  client/src/hooks/useGetList.tsx
  client/src/pages/ItemList.tsx
  client/src/pages/SearchList.js
  client/src/redux/slice/filterSlice.tsx
  client/src/redux/slice/nickNameSlice.tsx
  client/src/redux/slice/userSlice.tsx
  client/src/redux/store/store.ts
  client/src/types/auth.type.ts
  client/src/types/button.type.ts
  client/src/types/itemList.type.ts
  client/src/utils/ScrollToTop.tsx
  client/src/utils/axiosInstance.ts
  client/src/utils/makeParams.ts
Labels: 🐛 fix, ♻️ refactor, [FE] 방기현

#262 [Client] 타입스크립트 리팩터링 - Layout, Search + 중복 컴포넌트 제거
  client/src/components/Etc/Constants.js
  client/src/components/Etc/DefaultPayment.js
  client/src/components/Etc/PayDestination.js
  client/src/components/Etc/PayInfo.js
  client/src/components/Etc/PayMethod.js
  client/src/components/Etc/PayPageContainer.js
  client/src/components/Layout/Footer.js
  client/src/components/Layout/Footer.tsx
  client/src/components/Layout/Layout.tsx
  client/src/components/Layout/LeftNav.tsx
  client/src/components/Layout/RightNav.js
  client/src/components/Layout/RightNav.tsx
  client/src/components/Search/Search.js
  client/src/components/Search/Search.tsx
  client/src/pages/MyPages/OrderDetail.js
Labels: 🐛 fix, ♻️ refactor, [FE] 김세연

#267 [Client] 타입스크립트 리팩터링 - SearchList, Main 페이지
  client/src/components/Caroucel/CardCaroucel.tsx
  client/src/components/Etc/BrandsWindow.tsx
  client/src/components/Etc/PageTitle.tsx
  client/src/components/Etc/Price.tsx
  client/src/components/Etc/RecommendedTitle.tsx
  client/src/components/Lists/MainListCard.tsx
  client/src/pages/ItemList.tsx
  client/src/pages/Main/Home.tsx
  client/src/pages/Main/MainSection.tsx
  client/src/pages/SearchList.tsx
  client/src/redux/slice/userSlice.tsx
  client/src/types/auth.type.ts
  client/src/types/main.type.ts
  client/src/types/price.type.ts
Labels: 🐛 fix, ♻️ refactor, [FE] 방기현, 🎨 style

#270 [Client] 타입스크립트 리팩터링 - Tabs 및 에러 수정
  client/src/components/Etc/Constants.js
  client/src/components/Etc/PageTitle.tsx
  client/src/components/ItemSummary/Summary.js
  client/src/components/Layout/RightNav.tsx
  client/src/components/Lists/MyPageLists/CartList.js
  client/src/components/Lists/MyPageLists/SubManagementList.js
  client/src/components/Search/Search.tsx
  client/src/components/Tabs/DefaultToggleTab.tsx
  client/src/components/Tabs/MypageTab.tsx
  client/src/components/Tabs/ToggleTabs.tsx
  client/src/pages/MyPage.tsx
Labels: ♻️ refactor, [FE] 김세연, 🚚 rename

#269 [Client] 타입스크립트 리팩터링 - Forms
  client/.eslintrc.json
  client/src/components/Forms/DefalutForm.tsx
  client/src/components/Forms/ReviewForm.tsx
  client/src/components/Forms/TalkForm.tsx
  client/src/components/Forms/UpdateTalkForm.tsx
  client/src/types/button.type.ts
  client/src/types/form.type.ts
Labels: ♻️ refactor, [FE] 도현수, 🚚 rename
